TARGET = XTAG2
XCC_FLAGS = -O2 -DUSB_CORE=0 -g
APP_NAME =
USED_MODULES = module_xud module_usb_shared
VERBOSE = 0

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
